eclipse/scanning

- README.md
https://github.com/eclipse/scanning/issues/3
> Fix to README

- org.eclipse.scanning.command/scripts/mapping_scan_commands.py
Signed-off-by: Mark Booth <Mark.Booth@diamond.ac.uk>
> DAQ-492 (9.3pre) Fix bug in mscan due to change in scan_request

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IRunnableDevice.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/models/IDetectorModel.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/points/models/GridModel.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/AcquisitionDevice.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/watchdog/ExpressionWatchdog.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/watchdog/TopupWatchdog.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/All.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/AbstractMScanTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/MScanServletTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/SubmissionTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/epics/EpicsV4ConnectorTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/AbstractAcquisitionTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/AbstractWatchdogTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/ScanSpeedTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/SeekTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/ThreadScanTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/WatchdogCombinedTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/WatchdogShutterTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/WatchdogTopupTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/MandelbrotExampleTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/servlet/AbstractServletTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/servlet/ScanProcessTest.java
- sonar-project.properties
Trying to make tests be faster and more reliable.
> Test improvements

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/models/MalcolmModel.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmModel.java
Fix to the timeout of malcolm devices.
> Fix to malcolm model timeout and day default.

- org.eclipse.scanning.example.feature/org.eclipse.scanning.example.client.fat.product
- org.eclipse.scanning.example.feature/org.eclipse.scanning.example.client.product
- org.eclipse.scanning.example.feature/org.eclipse.scanning.example.server.product
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.target
- org.eclipse.scanning.third.feature/.gitignore
- org.eclipse.scanning.third.feature/.project
- org.eclipse.scanning.third.feature/build.properties
- org.eclipse.scanning.third.feature/feature.xml
Update target to use third party feature
> Target update

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/AbstractRunnableDevice.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmDevice.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/AcquisitionDevice.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/LocationManager.java
http://jira.diamond.ac.uk/browse/DAQ-413
Signed-off-by: Matthew Taylor <matthew.taylor@diamond.ac.uk>
> Fixes for pausing, resuming and progress updates on inner scans

- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.target
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/ScanAverageTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/ScanJythonTest.java
This should get travis tests running again.
> Update target platform target and fat target to January 2.0.0

- org.eclipse.scanning.points/src/org/eclipse/scanning/points/MultiStepIterator.java
> [DAQ-417] reimplemented MultiStepIterator to use jython array generator

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/points/models/CompoundModel.java
- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java
- org.eclipse.scanning.points/src/org/eclipse/scanning/points/CompoundSpgIterator.java
- org.eclipse.scanning.points/src/org/eclipse/scanning/points/ScanPointGeneratorFactory.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/epics/PVDataSerializationTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java
This reflects the change to CompoundGenerator in ScanPointGenerator
> Add duration to CompoundModel

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/points/models/OneDEqualSpacingModel.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/points/models/OneDStepModel.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/validation/ModelTest.java
> [DAQ-307] set names for 1D scan models and initialize to valid values

- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
> Log exception in ScanProcess.execute() as error not trace

- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
> [DAQ-538] set compound model duration to malcolm device exposure time

- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/NexusScanFileManager.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/SolsticeScanMonitor.java
Called from custom hooks in NexusScanFileManager. This is because it must always write to its unique keys dataset after all devices have written to their datasets.
> [DAQ-519] treat SolsticeScanMonitor separately from other monitors

- org.eclipse.scanning.points/META-INF/MANIFEST.MF
- org.eclipse.scanning.points/src/org/eclipse/scanning/points/validation/ScanRequestValidator.java
- org.eclipse.scanning.points/src/org/eclipse/scanning/points/validation/ValidatorService.java
> Fix to the validation to make it allow references to any valid device

- org.eclipse.scanning.points/scripts/jython_spg_interface.py
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/points/GridTest.java
> Use ScanPointGenerator structures to populate dimension_names

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/scan/LevelInformation.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/scan/LevelRole.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/DeviceRunner.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/DeviceWriter.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/LevelRunner.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/ScannablePositioner.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/AnnotationScanTest.java
> Added LevelRole to level information so that the type of level is known.

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/AbstractRunnableDevice.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IDeviceController.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IPausableDevice.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IRunnableDevice.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/AcquisitionDevice.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/watchdog/DeviceController.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
> Attempt to fix seek locking

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/bean/IBeanClassListener.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/bean/IBeanListener.java
- org.eclipse.scanning.event/src/org/eclipse/scanning/event/SubscriberImpl.java
> Attempt to fix events which are Heartbeat JSON and do not have a typeid.

- org.eclipse.scanning.points/scripts/jython_spg_interface.py
> Add comments to CPG deduplication code

- org.eclipse.scanning.points/src/org/eclipse/scanning/points/CompoundSpgIterator.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/DeviceRunner.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
I did this merge to get the timeout fix into master, but there were other unmerged commits as well.
Could @gerring and @mpdickie please check that you're happy for your 9.3 commits to go into master?
Thanks
> Master merge gda 9.3

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/models/ClusterProcessingModel.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/analysis/ClusterProcessingRunnableDevice.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/PyExpresserTest.java
Signed-off-by: Jacob Filik <jacob.filik@diamond.ac.uk>
> Expose xmx and timeout on cluster processing model

- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.target
URL to January repo changed. Updates all target platforms for new path.
> Changes January repository path to 2.0.1 since 2.0.0 disappeared

- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
The bean is also available as an injected field.
> Added ability to set latest bean directly during configure.

- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/CompositeNexusScannable.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockScannableConnector.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/CompositeNexusScannableTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/MalcolmScanTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/MandelbrotExampleTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/NexusTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/PerScanMonitorTest.java
> [DAQ-577] a first attempt at a simple composite nexus scannable

- org.eclipse.scanning.example/META-INF/MANIFEST.MF
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockNeXusScannable.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockNeXusSlit.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockStringNexusScannable.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/composite/ChildFieldNode.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/composite/ChildGroupNode.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/composite/ChildNode.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/composite/CompositeNexusScannable.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/MalcolmNexusScanFileManager.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/NexusScanFileManager.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/SolsticeScanMonitor.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/CompositeNexusScannableTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/NexusAssert.java
A kind of scannable that constructs its nexus objects from other
scannables.
> [DAQ-594] implement and test CompositeNexusScannable

- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
http://jira.diamond.ac.uk/browse/DAQ-618 details that monitors should not be automatically added.
> Fix for http://jira.diamond.ac.uk/browse/DAQ-618

- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/SolsticeConstants.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/SolsticeScanMonitor.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/NexusAssert.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/SolsticeScanMonitorTest.java
> [DAQ-625] add dead time and dead time percent to nexus file and log

- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java
> [DAQ-624] add file template to Malcolm device

- org.eclipse.scanning.test/OSGI-INF/mockDeviceConnector.xml
- org.eclipse.scanning.test/OSGI-INF/requesterPluginTest.xml
This reverts commit d9c9df18b59f56203249db09cbdc5e5656e7f5ab.
> Revert "Updates to plugin test OSGi files"

- org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/util/Stashing.java
This ensures that stash files are created in a place where both
client and server can access them.
> Use GDA var directory (if defined) for Solstice stashing

- org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/device/MonitorView.java
> [DAQ-609] improve tool-tip for filter active monitors toolbar button

- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat-stable.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb-stable.target
- org.eclipse.scanning.test/src/logback.xml
Changes to the scanning build environement. Improves target platform and fixes (minor) bug in logging. This has nothing to do with climate change.
> Make environment nicer

- org.eclipse.scanning.event/config/logback.xml
- org.eclipse.scanning.test/src/logback.xml
> Changes second logback.xml. Sets log level to INFO

- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java
> [DAQ-663] remove initial %s from file template passed to malcolm

- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java
> [DAQ-663] add h5 file extension to malcolm file template

- org.eclipse.scanning.test/src/org/eclipse/scanning/test/remote/RemoteQueueControllerServiceTest.java
> Removes unused import

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/AbstractRunnableDevice.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IRunnableDevice.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/scan/DeviceInformation.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/message/MalcolmUtil.java
- org.eclipse.scanning.event/src/org/eclipse/scanning/event/remote/_RunnableDevice.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmDevice.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmRecord.java
- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/remote/GetDeviceInformationTest.java
Changes to bring GDA inline with changes made to Malcolm
http://jira.diamond.ac.uk/browse/DAQ-674
Signed-off-by: Matthew Taylor <matthew.taylor@diamond.ac.uk>
> Updating GDA-Malcolm interface to latest

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/attributes/HealthAttribute.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/message/MalcolmUtil.java
- org.eclipse.scanning.connector.epics/src/org/eclipse/scanning/connector/epics/custommarshallers/NTScalarDeserialiser.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmDevice.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmRecord.java
- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java
- org.eclipse.scanning.points/src/org/eclipse/scanning/points/classregistry/ScanningAPIClassRegistry.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/MalcolmAttributesSerializationTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java
Added HealthMeta attribute
Removed busy endpoint
http://jira.diamond.ac.uk/browse/DAQ-674
Signed-off-by: Matthew Taylor <matthew.taylor@diamond.ac.uk>
> DAQ-674 Further Malcolm interface updates

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IDeviceWatchdogService.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/watchdog/DeviceWatchdogService.java
> Added method to get registered names to allow them to be printed

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/IQueueControllerService.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/QueueControllerService.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/QueueServiceSpringInitializer.java
- org.eclipse.scanning.event/src/org/eclipse/scanning/event/remote/_QueueControllerService.java
- org.eclipse.scanning.server/conf/server-fragment.xml
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueControllerServiceTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueProcessCreatorTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueProcessFactoryTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueResponseProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueServiceTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/_QueueControllerServiceTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/integration/QueueServiceInExampleServerTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/MonitorAtomProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/PositionerAtomProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/ScanAtomProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/SubTaskAtomProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/TaskBeanProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/remote/RemoteQueueControllerServiceTest.java
Another attempt to include the bridging class. This also attempts to fix the dodgy RemoteQueueControllerServiceTest.
> New run queue service in example (2)

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/IQueueBeanFactory.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/beans/SubTaskAtom.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/beans/TaskBean.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/QueueModelException.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/QueueableModel.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/SubTaskAtomModel.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/TaskBeanModel.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/arguments/IQueueValue.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/arguments/QueueListVariable.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/arguments/QueueTableVariable.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/arguments/QueueValue.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/arguments/QueueVariableDecorator.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/QueueBeanFactory.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueBeanFactoryTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/api/ModelArgsTest.java
Adds new factory to create queue atoms/beans for the queue service. This is the first part of the DB-QueueService integration.
> QueueBeanFactory

- .travis.yml
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/MonitorAtomProcessTest.java
This PR is to try things with Travis which might fix the 32-bit issues.
> Attempt to fix build

- org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/model/DatasetNameUtils.java
- org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/model/ModelFieldEditorFactory.java
* DatasetNameUtils: remove unused scheme argument in getDatasetInfo
> SCI-5908: refactor and enhance Conversion API

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/beans/MonitorAtom.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/processes/MonitorAtomProcess.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/processes/MonitorAtomProcessTest.java
Refactors MonitorAtomProcess and adds ability to set shape of data being recorded by monitor defined in MonitorAtom.
> Monitor atom update

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/scan/IFilePathService.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/file/MockFilePathService.java
> [DAQ-778] add method to IFilePathService to get visit config (xml) dir

- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmDevice.java
Signed-off-by: Jacob Filik <jacob.filik@diamond.ac.uk>
> Only validate file dir if set

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/models/DeviceModel.java
> Adds name field to DeviceModel and improves NPE protection

- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/ScanProcess.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/servlet/ScanProcessTest.java
> [DAQ-801] remove a monitor where that monitor is a scannable in the scan

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/database/ISampleDescriptionService.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/spooler/SpoolerServiceTest.java
@jamesmudd This is the initial commit of the SpoolerService interface which we talked about a week ago.
> Spooler service API

- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/analysis/ClusterProcessingRunnableDevice.java
Signed-off-by: Jacob Filik <jacob.filik@diamond.ac.uk>
> submit cluster processing on run rather than scan start

- org.eclipse.scanning.event.ui/src/org/eclipse/scanning/event/ui/view/StatusQueueView.java
Allow to realize actions which applies to a group of selected queue items.
> Add multi selection to the queue view

- org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/device/ScannableContentProvider.java
Signed-off-by: fajinyuan <fajin.yuan@diamond.ac.uk>
> I21-309 add scannable name to log message to identify object related.

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/status/StatusBean.java
- org.eclipse.scanning.event.ui/src/org/eclipse/scanning/event/ui/view/StatusQueueView.java
- org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/AcquisitionDevice.java
The column is updated when the task starts and the estimated end time is only considering the exposure time.
> Add estimated start and end times to queue view

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/models/AbstractDetectorModel.java
> Make Name field read-only in IGuiGeneratorService-generated GUIs

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/models/ScanMode.java
> [DAQ-504] implement toString for ScanMode to return user-friendly name

- org.eclipse.scanning.points/src/org/eclipse/scanning/points/MultiStepGenerator.java
as it is implemented in the jython scan point generation framework
> MultiStepGenerator.isScanPointGeneratorFactory should return true

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/filter/Filter.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/filter/FilterTest.java
> [DAQ-862] Fix filtering so that includes and/or excludes can be null

- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/DeviceRequestHandler.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/PositionerRequestHandler.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/core/IRequestHandler.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/core/IResponseCreator.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/scan/DeviceInformation.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/servlet/IResponderServlet.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/IMalcolmDevice.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/MalcolmConstants.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/MalcolmTable.java
- org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/attributes/MalcolmDatasetType.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/AbstractQueueRequestHandler.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/BeanStatusRequestHandler.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/GetQueueRequestHandler.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/GetServerStringRequestHandler.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/QueueResponseCreator.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/StartStopRequestHandler.java
- org.eclipse.scanning.event.queues/src/org/eclipse/scanning/event/queues/remote/package-info.java
- org.eclipse.scanning.event/src/org/eclipse/scanning/event/ResponderImpl.java
- org.eclipse.scanning.example/src/org/eclipse/scanning/example/malcolm/DummyMalcolmDevice.java
- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/AbstractMalcolmDevice.java
- org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmNexusObjectBuilder.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/AbstractResponderServlet.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/AcquireRequestHandler.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/AcquireServlet.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/DeviceServlet.java
- org.eclipse.scanning.server/src/org/eclipse/scanning/server/servlet/PositionerServlet.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/MalcolmAttributesSerializationTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueResponseProcessTest.java
- org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/DummyMalcolmDeviceTest.java
Mainly:
- moving malcolm constants from IMalcolmDevice to their own class
- renaming the *response classes to *RequestHandler
> A number of refactoring changes made while doing DAQ-504

- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat-stable.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb-stable.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb.target
Signed-off-by: Matthew Webber <matthew.webber@diamond.ac.uk>
> Update location of upstream p2 site

- org.eclipse.scanning.example.messaging/build.properties
- org.eclipse.scanning.example.xcen.ui/build.properties
- org.eclipse.scanning.example.xcen.ui/src/org/eclipse/scanning/example/xcen/ui/XcenPerspective.java
- org.eclipse.scanning.example.xcen.ui/src/org/eclipse/scanning/example/xcen/ui/XcenServices.java
- org.eclipse.scanning.example.xcen.ui/src/org/eclipse/scanning/example/xcen/ui/views/XcenView.java
These were seen with e4 oxygen and Java9 based on the new compliance
settings set in scanning.
> Fix to compile / configuration errors

- org.eclipse.scanning.event.ui/src/org/eclipse/scanning/event/ui/view/StatusQueueView.java
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat-stable.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb-stable.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb.target
- org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.target
Hiding them by default means that mscans are hidden by default, which
causes confusion when mscans do not show up in the status queue view.
appear
> Show all users scans by default in Scan Queue View
