eclipse/scanning

org.eclipse.scanning.points/scripts/scanpointgenerator/rois/polygonal_roi.py

A simple comparison error leads to an incorrect mask being generated,
resulting in invalid points being generated.
This exact fix has been made upstream, in ScanPointGenerator.

Fix masking bug in PolygonalROI in ScanPointGenerator

---

org.eclipse.scanning.points/scripts/jython_spg_interface.py

Name is a single string, not an array.

Fix ArrayGen name subscripting bug in SPG interface

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/AbstractScannable.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IScannableDeviceService.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/scan/DeviceInformation.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/Suite.java

Modify IScannableDeviceService.getDeviceInformation() so that in the
event of a failure to get information for a device, it just logs the
failure and continues with the remaining devices.
Previously, this threw an exception which could cause a scan to fail,
even if the failing device was not needed in the scan.

[DAQ-530] Tolerate exceptions getting DeviceInformations for scannables

---

org.eclipse.scanning.example/src/org/eclipse/scanning/example/detector/MandelbrotDetector.java

Stop the mandelbrot detector throwing an exception if real and imaginary axes are not defined as part of the scan, just return the data for 1,1. Allows the mandelbrot detector to be used in non-grid scans.

Make mandelbrot detector work for non grid scans

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/device/IScannableDeviceService.java

[DAQ-530] call handleDeviceError when cannot create DeviceInformation

---

org.eclipse.scanning.points/scripts/jython_spg_interface.py

When creating a compound generator from other compound generators
(occurs when creating a compound generator from the Java Iterator
classes that wrap compound generators), we should include any mutators
and excluders applied to those generators (the RandomOffsetGrid
produces a GridIterator with a RandomOffsetMutator applied to it for
instance).

Include nested excluders/mutators creating compound generators

---

org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/DeviceRunner.java

Previously, exposure time was used as timeout only if timeout had
been set negative. This changes the test to zero or negative
(so handling the cases where timeout has not been set) and also adds
an extra second to the timeout to allow for latency.

DAQ-524 Use exposure time as timeout for device if not explicitly set

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/points/AbstractPosition.java

These fields should not be visible to the user. The only fields
visible to the user should be, e.g. X, Y for a point.

[DAQ-575] Added UiHidden annotation to get methods in AbstractPosition

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/AbstractScannable.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/ITimeoutable.java
org.eclipse.scanning.command/OSGI-INF/services.xml
org.eclipse.scanning.command/scripts/mapping_scan_commands.py
org.eclipse.scanning.command/src/org/eclipse/scanning/command/Services.java
org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/ScannablePositioner.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/AbstractScanCommandsTest.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/MScanTest.java

Allowed the 'timeout' keyword arg to be used in scanning model commands. 
This sets the timeout on the axes directly and is not actually part of the model. The timeout is persisted and if set from the mscan command stays as the timeout for that scannable. Therefore it is really better to set the timeout property in spring.

Added timeout

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/AbstractScannable.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/CountableScannable.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/IScannable.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/ITolerable.java
org.eclipse.scanning.event/src/org/eclipse/scanning/event/remote/_Scannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockBeamOnMonitor.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockCountingPositionScannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockNeXusScannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockNeXusSlit.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockPausingMonitor.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockScannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockStringNexusScannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockStringScannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/MockTopupScannable.java
org.eclipse.scanning.example/src/org/eclipse/scanning/example/scannable/composite/CompositeNexusScannable.java
org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/ScannablePositioner.java
org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/SolsticeScanMonitor.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/annot/CountingDevice.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/AnnotationScanTest.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/SetPositionTest.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/Suite.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/ToleranceTest.java

In order to speed up Solstice motor moving (which has been reported as a real issue on more than one beamline) I intend to make two changes to it:
1.	Introduce a tolerance to IScannable
2.	Return a value from setPosition(…) which stops getPosition being called again
•	If a tolerance is non-null the position will be checked and the motor not moved. This still does a getPosition() call.
•	A IScannable may optionally return a position when it is moved which stops an additional getPosition() being called by the ExecutorService running the multi-threaded move.
[Method changes proposed to IScannable interface.]
The change will be done to mock IScannables and tests written to check the position calls are reduced. The class ScannableNexusWrapper which bridges GDA8 Scannables to Solstice will be …

Added ability for scannables to have tolerance and less getPositions (DO NOT MERGE)

---

org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/mock/MockOperationContextImpl.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/mock/MockSeriesRunner.java

These tests also implement the IOperationContext class from DAWN and so also needed to be updated accordingly
Signed-off-by: Tim Snow <tim.snow@diamond.ac.uk>

Modifications for defining number of threads/cores to run

---

org.eclipse.scanning.points/scripts/jython_spg_interface.py
org.eclipse.scanning.points/src/org/eclipse/scanning/points/AbstractScanPointIterator.java
org.eclipse.scanning.points/src/org/eclipse/scanning/points/CompoundSpgIterator.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/epics/PVDataSerializationTest.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/malcolm/real/ExampleMalcolmDeviceTest.java

Putting multiple regions into one excluder will consider the union of
the regions, rather than the intersection, when calculating scan
points. This is the behaviour "expected" of the GUI.
We can always add a means to "intersect" multiple regions later.
Note that an excluder can currently only cover two axes - so two
regions that cover different axes must necessarily have their
intersection considered, not their union.

DAQ-661 - Combine multiple ROIs into one excluder

---

org.eclipse.scanning.connector.epicsv3/src/org/eclipse/scanning/connector/epicsv3/EpicsV3DynamicDatasetConnector.java

make the monitorListener to handle color mode correctly - Note the original code only handle 'mono', 'rgb1', 'rgb2', and 'rgb3'. I have seen other detectors/camera in EPICS have other color mode values.

DAQ-669 fix DBR_Enum cast to DBR_String error

---

org.eclipse.scanning.test/META-INF/MANIFEST.MF

Needed to use ScanningTestClassRegistry in Mapping UI tests

Export package org.eclipse.scanning.test from plugin of same name

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/connector/MalcolmMethod.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/connector/MessageGenerator.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/malcolm/message/MalcolmMessage.java
org.eclipse.scanning.connector.epics/src/org/eclipse/scanning/connector/epics/EpicsV4MalcolmMessageGenerator.java
org.eclipse.scanning.connector.epics/src/org/eclipse/scanning/connector/epics/custommarshallers/MalcolmMessageSerialiser.java
org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/AbstractMalcolmDevice.java
org.eclipse.scanning.malcolm.core/src/org/eclipse/scanning/malcolm/core/MalcolmDevice.java

[DAQ-675] use MalcolmMessage enum instead of inspecting stack trace

---

org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat-stable.target
org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.fat.target
org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb-stable.target
org.eclipse.scanning.target.platform/org.eclipse.scanning.target.platform.ispyb.target

New release version of DAWN (still 2.5, just a new build) and also JDBC
for the ISPyB TPs. Updates TP to match both.
Now with updated head

Updates DAWN in stable and volatile target platforms (2)

---

org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/nexus/NexusAssert.java

Nexus now writes scalar datasets correctly. Previously they were written
as datasets of rank 1 and size 1. So we can remove the workaround that
allows this case when comparing the nexus tree loaded from the file
with the original.

remove workaround for scalar datasets when asserting datasets equal

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/database/ISampleDescriptionService.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/queues/IQueueSpoolerService.java
org.eclipse.scanning.event.queues.spooler/src/org/eclipse/scanning/event/queues/spooler/QueueSpoolerService.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/QueueSpoolerServiceTest.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/event/queues/mocks/MockSampleDescriptionService.java

A second attempt...
Adds the IQueueSpoolerService and stub implementation, as well as test for Emilio. Changes ISampleInformationService to require returning of concrete classes so it can be used inside other parts of scanning.
Signed-off-by: Michael Wharmby michael.wharmby@diamond.ac.uk

Queue spooler stub & ISampleInformationService update (2)

---

org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/DeviceRunner.java

Modify DeviceRunner.getTimeout() so that, if no explicit timeout
is set for a detector, it is set to (exposure time + 1s), rounded up
(Math.ceil()), rather than (potentially rounded down (Math.round()).
Also remove the test for IDetectorModel, as this is an extension
of ITimeoutable, which is tested for above, so this code will never
be executed.

[DAQ-758] Correct calculation of device timeout

---

org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/composites/MultiStepComposite.java

When the composite is fixed to a single scannable and the name combo is disabled
it would be nice to be able to call this to set the correct units.

Make MultiStepComposite::updateUnits public

---

org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/LevelRunner.java

We had a few instances where exception appeared to be swallowed, so
this log message will help us identify cases where the abortException
is reset before it is re-thrown.

Log when LevelRunner.abortException is reset.

---

org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/composites/StepModelComposite.java

This would happen when scannable.getMinimum() and/or scannable.getMaximum() are null. In this change, we return from setBounds if these are values are null.

Avoid NPE in StepModelComposite

---

.travis.yml

Travis switched to SonarJava 4.12 rather than SonarJava 4.11 which
requires sonar.java.binaries to be set if mvn sonar:sonar isn't run.

Update Eclipse Scanning Travis and SonarCloud support.

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/points/models/AbstractBoundingBoxModel.java

This was causing event loops, which stop the scan path calculation
working in the Mapping perspective.

Remove firing of PCS when setBoundingBox is called

---

org.eclipse.scanning.event.ui/src/org/eclipse/scanning/event/ui/view/StatusQueueView.java

This is required because the file is not opened in non-SWMR mode

Disable link to the result when the scan is running

---

org.eclipse.scanning.sequencer/META-INF/MANIFEST.MF

If this bundle does use commons logging somehow it should be using the
slf4j bridge anyway

Remove unneeded commons logging dependency

---

org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/nexus/NexusScanFileManager.java

Log a warning instead of throwing an exception

[DAQ-837] Make scanning more robust to errors in per-scan monitors

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/filter/Filter.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/filter/FilterService.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/scan/ui/AbstractControl.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/scan/ui/ControlTree.java
org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/device/scannable/ControlTreeViewer.java
org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/device/scannable/ControlValueLabelProvider.java
org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/device/scannable/NameEditingSupport.java

The principal changes here are:
- Give each action (Add group, Add control, Remove) an id.
This allows (for example) the dialogue to edit the beamline
configuration to remove actions it does not want to support.
- Check for null pointers/empty strings in ControlValueLabelProvider
& NameEditingSupport 
Other changes:
- Improved toString() functions in AbstractControl & ControlTree

[DAQ-841] Improvements to usability of ControlTreeViewer

---

org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/composites/MultiStepComposite.java

This would happen when the widget is tied to a single scannable, making
the filter inappropriate.

[DAQ-867] If model name is not in filtered scannable list, do not filter

---

org.eclipse.scanning.command/src/org/eclipse/scanning/command/factory/MultiStepModelExpresser.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/command/PyExpresserTest.java

Basically add missing keyword when verbose. Also removed already completed TODO.

DAQ-918 Fix inconsistent python expression for MultiStepModel

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/event/scan/ScanRequest.java

This should be a temporary measure to avoid flooding Graylog with these
messages, the real question is why is this method called so often.
Currently in Graylog there are ~68M of these messages
https://graylog.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1920&relative=432000&q=loggerName%3Aorg.eclipse.scanning.api.event.scan.ScanRequest#fields=message%2Csource
and as there are also large messages they are shortening the history for
everyone.

DAQ-903 Reduce logging message to trace

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/DeviceAnnotations.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/FileDeclared.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/LevelEnd.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/LevelStart.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/PointEnd.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/PointStart.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/PostConfigure.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/PreConfigure.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanAbort.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanEnd.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanFault.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanFinally.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanPause.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanResume.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/ScanStart.java
org.eclipse.scanning.api/src/org/eclipse/scanning/api/annotation/scan/WriteComplete.java

Remove the duplicated, undifferentiated javadoc in each annotation, and
replace it with indiviual javadoc for each annotation, plus a link to
the DeviceAnnotation class javadoc which contains a the javadoc which
was duplicated elsewhere.
This should make it easier to use these annotations and keep the javadoc
up to date.

Improve javadoc for DeviceAnnotations

---

org.eclipse.scanning.sequencer/src/org/eclipse/scanning/sequencer/watchdog/ExpressionWatchdog.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/WatchdogCombinedTest.java
org.eclipse.scanning.test/src/org/eclipse/scanning/test/scan/WatchdogShutterTest.java

Before this change, a scan which was started while ExpressionWatchdog
evaluated to false would throw ScanningException and fail. Now, the job
would simply be paused until the expression evaluates to true.

ExpressionWatchdog: let job be paused from start

---

org.eclipse.scanning.points/scripts/scanpointgenerator/core/compoundgenerator.py
org.eclipse.scanning.points/scripts/scanpointgenerator/core/dimension.py
org.eclipse.scanning.points/scripts/scanpointgenerator/core/excluder.py
org.eclipse.scanning.points/scripts/scanpointgenerator/excluders/roiexcluder.py
org.eclipse.scanning.points/scripts/scanpointgenerator/generators/__init__.py
org.eclipse.scanning.points/scripts/scanpointgenerator/generators/nullpointgenerator.py

Changes since 2.1 release are the allowing of excluders on
non-consecutive generators, and the addition of the "continuous"
property on CompoundGenerator.
This also includes a WIP version of "NullPointGenerator" (name subject
to change) - this is a generator with no axes that produces empty
points - it can be put into a CompoundGenerator on its own, or
included with other generators, in which case it will "repeat" the
generators given after it (adding an additional Dimension).

Update scanpointgenerator to Pull Request #48 (commit 380fa87e)

---

org.eclipse.scanning.api/src/org/eclipse/scanning/api/scan/ui/AbstractControl.java

Adding a group to 'Configure beamline' dialog in Mapping UI caused NPE
thrown in AbstractControl :: contains (getName() returned null). Simple
reordering prevents this.
Refactored contains and toPosition slightly to fix Sonar complexity warnings.

Reorder expression to prevent NPE

---

org.eclipse.scanning.device.ui/src/org/eclipse/scanning/device/ui/device/scannable/ControlValueCellEditor.java

The method setPosition was causing problems the second time it was called
(the first tied to the SWT.Traverse event, the second by focusLost) due
to the tooltip being disposed. I have added isDisposed() to the if statement.

Do not attempt to access a disposed widget

---

org.eclipse.scanning.points/src/org/eclipse/scanning/points/serialization/PositionBean.java
org.eclipse.scanning.points/src/org/eclipse/scanning/points/serialization/PositionDeserializer.java
org.eclipse.scanning.points/src/org/eclipse/scanning/points/serialization/PositionSerializer.java

A previous change attempted to restore IPositions to the same class as
previously, i.e. one of StaticPosition, Scalar, Point or MapPosition.
This was done by adding a positionClass field to PositionBean.
This causes a ClassNotFoundException for MapPosition for some reason,
so this change reverts that change. Another fix would have been to
use a string for the class, but this could have a performance impact.

[DAQ-1030] fix deserializing IPosition, broken in earlier change
